version: '3'
services:
    nginx:
        container_name: nginx
        restart: always
        build:
            context: ./.docker/nginx
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        links:
            - php-fpm
        networks:
            - code-network

    php-fpm:
        container_name: php-fpm
        restart: always
        build:
            context: ./.docker/php74
            dockerfile: Dockerfile
        expose:
            - "9000"
        volumes:
            - ./:/var/www
        networks:
            - code-network

    mysql:
        container_name: mysql
        restart: always
        build:
            context: ./.docker/mysql
            dockerfile: Dockerfile
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - ${MYSQL_DATA}:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
